# name: NASA PROJECT CI
# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Use NodeJS version 16
#       - uses: actions/setup-node@v2
#         with:
#           node-version: 16
#       - run: npm install
#       - run: npm run build --prefix client

name: NASA PROJECT CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    env:
      CI: true
      MONGODB_LOCAL_URL: mongodb://localhost/nasa
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        mongodb-version: ['4.4']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use MongoDB from GitHub actions
      - uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm install --prefix server
      - run: npm install --prefix client
      - run: npm run build --prefix client
      - run: npm test --prefix server
      - run: npm test --prefix client
